# Generated by Django 2.2.1 on 2019-05-17 12:48

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=6)),
                ('nombre', models.CharField(max_length=60)),
                ('creditos', models.IntegerField()),
            ],
            managers=[
                ('cursos', django.db.models.manager.Manager()),
            ],
        ),
    ]
